# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=75)),
                ('description', models.TextField()),
                ('unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_acquired', models.DateField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeProfile')),
                ('issued_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to='employee.EmployeeProfile')),
                ('recieved_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by', to='employee.EmployeeProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
