# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170930_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
