# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='property_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
