# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_auto_20170822_2231'),
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date_listed', models.DateField()),
                ('quantity', models.IntegerField()),
                ('employee_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attended', to='employee.EmployeeProfile')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_harvest', to='fish.Fish')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
