# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20170930_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
