# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20171015_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='employee_attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee Assisted'),
        ),
    ]
