# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('time_in_am', models.TimeField(blank=True, null=True)),
                ('time_out_am', models.TimeField(blank=True, null=True)),
                ('time_in_pm', models.TimeField(blank=True, null=True)),
                ('time_out_pm', models.TimeField(blank=True, null=True)),
                ('extra_time_in', models.TimeField(blank=True, null=True)),
                ('extra_time_out', models.TimeField(blank=True, null=True)),
                ('total_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('employee', 'date')]),
        ),
    ]
