# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_auto_20170809_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in_am', models.TimeField()),
                ('time_out_am', models.TimeField()),
                ('time_in_pm', models.TimeField()),
                ('time_out_pm', models.TimeField()),
                ('notes', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
