# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20170809_1704'),
        ('attendance', '0002_auto_20170809_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('employee', 'date')]),
        ),
    ]
