# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170925_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
