# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20170927_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_of_absence',
            field=models.CharField(blank=True, choices=[('OB', 'Official Leave'), ('SL', 'Sick Leave'), ('VL', 'Vacation Leave'), ('SIL', 'Service Incentive Leave'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('PAL', 'Parental Leave'), ('RL', 'Rehabilitation Leave'), ('STL', 'Study Leave')], max_length=3),
        ),
    ]
