# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('scientific_name', models.CharField(blank=True, max_length=75)),
                ('image', models.ImageField(max_length=150, upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
