# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, max_length=150, upload_to=b''),
        ),
    ]
