# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=b''),
        ),
    ]
