# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20170822_2209'),
        ('fish', '0003_auto_20171002_2222'),
    ]

    operations = [
    ]
