# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_merge_20171003_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fish/'),
        ),
    ]
