# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_auto_20171007_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fish.Category'),
            preserve_default=False,
        ),
    ]
