# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0007_fish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
