# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0008_auto_20171012_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='cost_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
