# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(default='tanay', max_length=30),
            preserve_default=False,
        ),
    ]
