# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_order', to='fish.Fish'),
        ),
    ]
