# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0002_auto_20170925_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment',
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(to='dispersal.Payment'),
        ),
    ]
