# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 12:39
from __future__ import unicode_literals

import dispersal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0003_auto_20171015_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=dispersal.models.increment_invoice_number, max_length=500, null=True),
        ),
    ]
