# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0003_auto_20170925_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
