# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0004_auto_20171015_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
