# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0005_auto_20171017_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('I', 'REGION I (Ilocos Region)'), ('II', 'REGION 2 (Cagayan Valley)'), ('III', 'REGION III (Central Luzon)'), ('IV-A', 'REGION IV-A (CALABARZON)'), ('IV-B', 'REGION IV-B(MIMAROPA)'), ('V', 'REGION V(Bicol Region)'), ('VI', 'REGION VI (Western Visayas'), ('VII', 'REGION VII (Central Visayas'), ('VIII', 'REGION VIII (Eastern Visayas)'), ('IX', 'REGION IX (Zamboanga Peninsula)'), ('X', 'REGION X (Northern Mindanao)'), ('XI', 'REGION XI (Davao Region)'), ('XII', 'REGION XII (Soccsksargen)'), ('XIII', 'REGION XIII (CARAGA)'), ('NCR', '(NCR) National Capital Region'), ('XIV', 'REGION 14 Cordillera Administrative Region (CAR)'), ('XV', 'REGION XV - Autonomous Region in Muslim Mindanao (ARMM)'), ('XVIII', 'Region XVIII - NIR - Negros Island Region')], default='NCR', max_length=5),
        ),
    ]
