# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0006_auto_20170927_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
