# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersal', '0010_auto_20171002_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='free',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
