# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionList',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sessions.Session')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
            bases=('sessions.session',),
        ),
    ]
