# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20170822_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='picture',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=b''),
        ),
    ]
