# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_sessionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlist',
            name='session_ptr',
        ),
        migrations.DeleteModel(
            name='SessionList',
        ),
    ]
