# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20170809_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='finger_print',
            field=models.BooleanField(default=False),
        ),
    ]
