# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='picture',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='employee/'),
        ),
    ]
