# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20171007_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='picture',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='employee/'),
        ),
    ]
